fix(git): merge-log-d now forces delete branch
Sinon ça déconne quand la remote branch est pas synchro.

Voila ce qui m'est arrivé:

git merge-log-d feat/csv
Merge made by the 'ort' strategy.
 Makefile                        |  2 ++
 README.md                       |  3 +++
 lcad/parsers/csv.py             | 85 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 tests/fixtures/list_of_dict.csv |  3 +++
 tests/fixtures/list_of_list.csv |  3 +++
 tests/parsers/test_csv.py       | 20 ++++++++++++++++++++
 6 files changed, 116 insertions(+)
 create mode 100644 lcad/parsers/csv.py
 create mode 100644 tests/fixtures/list_of_dict.csv
 create mode 100644 tests/fixtures/list_of_list.csv
 create mode 100644 tests/parsers/test_csv.py
warning: not deleting branch 'feat/csv' that is not yet merged to
         'refs/remotes/origin/feat/csv', even though it is merged to HEAD.
error: The branch 'feat/csv' is not fully merged.
If you are sure you want to delete it, run 'git branch -D feat/csv'.
fatal: There is no merge to abort (MERGE_HEAD missing).
θ63° [sam:~/Code/github.samk/lcad]\2 master(2)+ 2s 128 ± git lg
*   ea38655 - (2024-08-13 14:56:55 +0200) Merge branch 'feat/csv' [Samuel Krieg] (HEAD -> master)
|\
| * a000df3 - (2021-07-09 17:45:41 +0200) feat: add CSV support [Samuel Krieg] (feat/csv)
|/